// Cards Against Humanity - Deck de Cartas em Português do Brasil (Customizado via Google Docs)

const blackCards = [
  "Eu como _____ no café da manhã. Tem gosto de frango.",
  "________ é lindo como __________.",
  "50 tons de _.",
  "Toc, toc. Quem é?",
  "Ontem eu vi a Anitta no _____.",
  "Estou louco para _________.",
  "Racismo é bom pra _________.",
  "Comprei um PS4 mas tive que dar ______ para conseguir comprar um jogo.",
  "É algum crime ________?",
  "Não sabia que ________ era tão bonito.",
  "Quem nunca teve ________?",
  "Bandido bom é _________.",
  "A Copa de 2014 foi uma ______.",
  "Eu brochei por causa de ________.",
  "Dadinho é o caralho. Meu nome agora é _______, porra!",
  "Eu tentei tirar uma foto com a Xuxa mas não deu porque _________ tava lá.",
  "A minha mulher é uma puta porque ela não me fez _______.",
  "Abri uma loja para vender ________.",
  "Um dia vou ficar rico com este simples truque de __________.",
  "Tentei roubar dinheiro mas o Super _________ apareceu e bateu em mim.",
  "________________",
  "Lula é inocente porque ______.",
  "Não sei nadar mas não é problema porque tenho um _________.",
  "Não há nada mais foda que ___________.",
  "Descobri que o Skype também serve para _________.",
  "Gostei de ________. Faria de novo.",
  "Flagrei meu filho se preparando pra _______.",
  "Droga! Estou cercado de __________!",
  "Homem que é homem não vai a ________.",
  "Você me pediu hambúrguer. Eu te trouxe _________.",
  "Olha este pokémon que apanhei! É o _________!",
  "Quero agradecer ao meu amigo ________ por _______.",
  "Quem me dera ter aqui um __________.",
  "_________ e _________: combinação explosiva.",
  "Nova moda da nação: _______.",
  "Quando penso em ________, penso sempre em ________.",
  "Dinheiro não compra amor, mas compra __________.",
  "No 8º dia, o Senhor criou __________.",
  "Qual o mais crocante? _______ ou ________?",
  "Quem participou na orgia do vizinho?",
  "________ é uma boa ideia para um excelente filme de família",
  "________________",
  "Eles dois me fazem lembrar _________.",
  "Coelhinho da páscoa que trazes pra mim?",
  "BBB seria mais divertido se tivesse ______.",
  "Odeio _______.",
  "Para sermos melhores pessoas, devemos fazer __________.",
  "Quando eu crescer quero ser _________.",
  "Já não faço ____________ há anos.",
  "O meu maior sonho é __________.",
  "A grande novidade do Iphone 17 é ___________.",
  "Aquele que controla _________ controla o mundo",
  "A ciência nunca vai explicar ___________.",
  "Não sou capaz de sair de casa sem ________.",
  "Armas não matam pessoas. ________, sim.",
  "Escovo meus dentes com _________.",
  "O familiar sabor de _________.",
  "O Regime Militar deveria voltar porque __________.",
  "_________ > _________ .",
  "Olha aí, não se goza com _________.",
  "Olha para mim, sou sexy e _________.",
  "O nome da \"Igreja Católica\" mudou para \"______ Católica\" para atrair o público mais jovem",
  "O tribunal declarou que _________ é culpado de _________.",
  "_______ e  _________ fazem um almoço equilibrado.",
  "A nossa relação é estritamente platônica. Não quero estragar com ________.",
  "Proibidos de se masturbarem, os padres canalizam os seus desejos reprimidos para _________.",
  "________, o grande prazer da vida.",
  "________ devia de ser legalizado.",
  "Tenho de voltar rápido para casa ou vou perder __________.",
  "Odeio quando os meus professores mandam __________.",
  "___________ nunca fez algo de errado.",
  "Espera! Não vai! Falta __________.",
  "Por que é que tem de ser tão ________?",
  "Uma boa dose de ________ faz bem e faz crescer.",
  "Voltando pro meu quarto depois da festa, encontrei _________ na minha cama.",
  "Para sermos melhores pessoas, devemos fazer __________.",
  "Se voltasse atrás no tempo gostaria de ________ em algum lugar histórico.",
  "Os meus planos de dominação mundial começam com _________.",
  "Fui para África e levei o meu _______ para ajudar as pessoas que vivem lá.",
  "África é um lugar muito legal, o problema é que tem muito ________.",
  "Gosto de ________ quando cuido de pessoas com síndrome de down.",
  "Mais vale um _______ na mão, do que um _______ voando",
  "Mudou-se a primeira frase do hino nacional para _________.",
  "A minha mãe sempre me dizia: ________.",
  "Quem não tem colírio usa __________.",
  "Aprendi da pior maneira que não pode ajudar um amigo triste com ________.",
  "No futuro, historiadores vão concordar que _______ marcou o começo do declínio do Brasil.",
  "O exército brasileiro interroga agora os agentes inimigos submetendo-os sucessivamente a ________.",
  "O segredo para um casamento bem sucedido é comunicação, e __________.",
  "Quando tudo falha, posso sempre me masturbar vendo _______.",
  "Genialidade é 10% inspiração e 90% _______.",
  "Todos de pé! Braços pra cima! Vamos cantar! _________",
  "Você. Eu. _______. Agora.",
  "190, qual a emergência?",
  "Este local de trabalho está há 0 dias sem ________.",
  "Lembrem-se crianças: Não coloquem ______ nas suas vaginas.",
  "Eu não sou racista, só não gosto de _________.",
  "Enquanto mijo gosto de ver _________.",
  "Se eu pudesse comia _______ em todas as refeições.",
  "_________? Isso foi o que a sua mãe me disse ontem",
  "O prato de hoje do menu vegetariano é _________.",
  "Eu fui preso no Natal porque _________.",
  "________________",
  "_________ é definitivamente 10/10.",
  "Escola é para os _________.",
  "Um dia vou ser o primeiro a criar ________.",
  "A minha escola precisa mesmo de um clube de _________.",
  "Vamos fazer ________, e Cuba vai pagar.",
  "Passei muitos dias na universidade fazendo ______.",
  "Adivinha!?!? Encontrei __________.",
  "Achas que os romanos tinham um Deus para __________?",
  "Segundo a última edição da revista Caras, qual a coisa que os homens mais desejam?",
  "_________ queima 500 calorias numa hora.",
  "Na universidade quero estudar _______.",
  "As coisas que não deviam existir: ______, ________ e __________.",
  "Odeio admitir isto, mas já tive uma ereção devido a ________.",
  "Não posso acreditar que __________ aconteceu comigo outra vez.",
  "Não consigo acreditar que o meu próprio país tem orgulho em _________.",
  "Parece que afinal _______ era uma coisa comum de se fazer nos anos 60.",
  "O maior desastre natural este ano envolveu ___________.",
  "Eu acredito pessoalmente que ________ é contra o código moral humano.",
  "Um dia quero criar um parque temático baseado em __________.",
  "________. Não tente isto em casa.",
  "________________",
  "Foram reportados vários homicídios, todos cometidos por ____________.",
  "O que é que os diretores pornos usam para se masturbar?",
  "Devíamos culpar ________ por tudo.",
  "Resolução de Ano Novo: Menos _______, mais ________.",
  "_______ contra _______: O novo drama original produzido pelo",
  "SBT",
  "O meu amigo é viciado em _____! Ajudem!",
  "Eu dei o meu coração e ela me deu ______.",
  "Qual a coisa em que o sexo oposto é bom?",
  "Um homem foi condenado a prisão perpétua depois de ser acusado de __________.",
  "_________ é geralmente a principal causa de depressão",
  "Uma pizza só é boa se for acabada com uma pitada de _________.",
  "________ é supervalorizado",
  "Nunca pensei ver _______ na convenção de ________.",
  "Em pelo menos 3 países _________ é ilegal.",
  "Quando vou ao McDonald's peço sempre _________.",
  "Eu pedi ao vendedor 10kg de ________ mas em vez disso ele me deu 10kg de ________!",
  "_________. Um sinal que o mundo está para acabar.",
  "O meu pai me deixou _______ no testamento.",
  "O que é que irrita uma feminista?",
  "______ é o meu ingrediente favorito para fazer sundaes.",
  "________________",
  "O pequeno João encontrou _______ na internet no famoso site _________.com.",
  "Os meus filhos precisam descobrir _________.",
  "________ + ________ = Felicidade",
  "Já dizia o meu avô mudo: \"__________\".",
  "Prostituição não leva a nada a não ser __________",
  "É melhor se calar ou o meu irmão mais velho vai te dar __________.",
  "Um grande hobby para os deficientes mentais: __________.",
  "Vou vender a tua alma pro Satanás para conseguir _________.",
  "______ é a única coisa que poderia meter dentro de mim.",
  "O que acabou com o reinado de terror de Satanás?",
  "Um homem chega em casa, bate na mulher e grita: \"_____\"",
  "Passei anos e anos praticando _________.",
  "O que é que os argentinos são bons pra fazer?",
  "Não quero nada caro, apenas __________",
  "O que é que o Ronaldo Fenômeno tinha na mão quando nasceu?",
  "Um vidente disse que Neymar ia viver uma vida cheia de ________.",
  "Lista de compras: pão, leite, ovos, água, _______ e batatas.",
  "Durante o sexo, gosto de gritar \"_________\".",
  "Sabes o que é que me faz broxar?",
  "Provavelmente deveria ter tirado _ do meu currículo.",
  "________________",
  "Só tenho dois desejos na minha vida: ________ e ________.",
  "Está na hora de experimentarmos _________.",
  "Para o meu próximo truque, preciso de um preservativo e de ________.",
  "____________ definitivamente cumpre as expectativas",
  "Pode ser estranho, mas acho que _____ faz a minha namorada mais sexy",
  "Nunca aprendi como ______ na escola.",
  "Só o meu pai sabe o quanto eu gosto de __________.",
  "Hoje, apenas vou ser eu, o meu amor e ___________.",
  "Quando vi a tua mãe nua, me lembrei de __________.",
  "Precisa de duas coisas para sobreviver na África: _____ e _______.",
  "Encontrei ________ no quarto da avó!",
  "PÁRA! Em nome de _______",
  "Não se deve colocar ________ na boca!",
  "O meu médico diz que _______ cura tudo.",
  "Já dizia o Raul, 1500 reais não dá para ______.",
  "A palavra chave é: ________.",
  "Perdi a _______ na areia.",
  "Eu só aceitaria trocar a minha coleção privada de pirilampos mágicos por __________.",
  "O sonho molhado da Marina Ruy Barbosa é :_________.",
  "Tenho de voltar o mais depressa possível para casa ou vou perder ______.",
  "________________",
  "_______. Foi assim que Camões perdeu o seu olho.",
  "_______ é o heterónimo menos conhecido de Fernando Pessoa.",
  "Só por curiosidade, vendem ______ no vosso estabelecimento?",
  "Fiquei completamente pardo quando a Maria sugeriu experimentar ______ logo à noite.",
  "O assassino em série António Machado ficou conhecido por dizer \"_______\".",
  "Os historiadores continuam até hoje a esconder a verdadeira razão do terremoto de 1755: ______.",
  "O que é extremamente raro mas as pessoas pensam que é comum?",
  "Que habilidade poderia um rapaz pobre de 19 anos aprender para ir ganhando uns trocados?",
  "Qual a coisa mais assustadora e aterrorizadora que existe?",
  "O que é comum no Rio, mas não em São Paulo?",
  "A pior coisa que vi durante um voo da TAM foi _________",
  "Como é que se supera a depressão?",
  "Qual a melhor maneira de quebrar o gelo?",
  "Como sair de situações constrangedoras?",
  "Se pudesse escolher, quais seriam as suas últimas palavras?",
  "Qual o seu maior medo que ninguém entende?",
  "O mundo acaba dentro de 1 hora. O que fazes?",
  "Qual a coisa mais estranha que já encontrei enquanto fazia uma cirurgia?",
  "Que atividades são divertidas num grupo de 4 pessoas?",
  "O que não acha atraente?",
  "________________",
  "O que gosta mais no nosso Brasil?",
  "Que disciplina devia estar no currículo escolar?",
  "O que recebe má reputação injustamente?",
  "Que importantes fatos históricos os livros de história omitem?",
  "Qual a coisa que é apropriado para crianças mas não para adultos?",
  "O senado pensa em banir _______ pois foi usado numa escola cheia de crianças.",
  "Perdi a minha inocência quando vi ________ pela primeira vez na internet.",
  "________ é o que ainda mantém o nosso casamento vivo",
  "_______. Prova que Deus te odeia.",
  "Esta semana, os Teletubbies ensinaram __________.",
  "_________ é apenas outra maneira de dizer _______.",
  "Após rever os desenhos animados da minha infância, reparei que todos têm referências subtis sobre __________",
  "Eu preciso de feminismo porque ___________",
  "Eu só tenho um Deus, o Deus do ____________",
  "Eu tenho uma espécie de Toque de Midas, mas em vez de ouro, tudo o que toco transforma-se em ________",
  "Fazer amor comigo é como ___________",
  "O Natal foi cancelado devido a _________.",
  "Não, _______ não é uma presente de aniversário para uma criança de 5 anos.",
  "Deixa sempre ______ na mesa para o empregado saber que prestou um bom serviço.",
  "Bem... Parece que meter ________ no microondas não foi lá muito boa ideia.",
  "________________",
  "Os sindicatos estão pedindo greve outra vez. Pedem mais benefícios, melhores salários e _____",
  "A coisa mais branca de sempre: ______",
  "O próximo jogo de sexta à noite em família: ___________",
  "A noite é escura e cheia de ____________.",
  "__________ vai mudar a forma como olhamos para a medicina moderna",
  "Os investigadores da PF ficaram surpreendidos quando encontraram _________ no congelador do assassino.",
  "Devido a um trauma de infância, tenho um medo profundo de __________",
  "Se pudesse disparar qualquer coisa dos meus dedos, seria __________",
  "A votação acabou. O novo esporte olímpico será ____________",
  "Dica: quando o teu patrão olhar de forma suspeita, responde com __________.",
  "A lista de compras da minha avózinha: 1- Leite, 2- Pão, 3- ___________",
  "Encontrei um preto num beco tentando me vender ______.",
  "O meu cosplay de ________ foi um sucesso na convenção de __________.",
  "Tenho um fetiche muito estranho. Eu  me excito com a ideia de ser transformado em ________",
  "Tenho fotos incriminatórios da pessoa a minha esquerda fazendo ______.",
  "A papelaria Fernandes decidiu expandir o negócio e começar a vender _______",
  "Preciso de um advogado com experiência em __________.",
  "_______ é uma péssima maneira de demonstrar a tua gratidão.",
  "Médicos agora dizem que ______ é de fato bom para a saúde, em quantidades pequenas",
  "Vivemos na era de ________. A tecnologia é incrível",
  "________________",
  "O PT tem o controle total de ___________.",
  "A pessoa a minha direita pensa que o mundo ficaria melhor sem ___________",
  "__________ é difícil de engolir para a maioria das pessoas.",
  "Todos os canais estão a reportar a mesma notícia: ___________",
  "Tenha estado muito estressado ultimamente, mas _______ alivia a pressão",
  "Porque é que os meus amigos me removeram do Facebook?",
  "Atirem as suas cartas para o vazio.",
  "_________.",
  "_________.",
  "_________.",
  "_______ é a razão pela qual a minha mãe é ___________.",
  "________ é ok desde que não tente ________.",
  "Nunca use _______ como lubrificante.",
  "A única teoria de conspiração que posso talvez acreditar é _________.",
  "Por que a galinha atravessou a rua?",
  "__________ é uma forma de medicina africana.",
  "O Ministério da Saúde publicou recentemente um estudo sobre uma nova doença chamada _____.",
  "Quando aceitei completamente a ideia de _______, me senti livre.",
  "Há bastantes provas de _________.",
  "Provavelmente é autista se gosta de _____.",
  "_________ cheira a _________",
  "Espero nunca ser raptado por extraterrestres e ser sondado por _________.",
  "O que é pior do que encontrar uma minhoca na sua maçã?",
  "________________",
  "Perdi interesse em _________ depois de __________",
  "_________ são notícias falsas.",
  "A vida nunca foi a mesma depois de ______ ter sido diagnosticado com ________.",
  "Todas as vezes que eu _______, penso em você.",
  "Hoje pensei em ________, mas tenho uma mulher e filhos.",
  "A caminho de _________ vimos _________.",
  "2009 foi há uma década. Como é que isso te faz sentir?",
  "O que é que eu penso do Norte?",
  "Desculpa, mas tenho uma fobia incontrolável de ___________.",
  "O meu pior sonho de sempre envolve ___________",
  "A minha fantasia mais marota é __________",
  "Esta carta ganha sempre: ___________.",
  "Tenho receio que você tenha _________. Só tem mais 5 meses de vida",
  "Pensar sobre ____________ irá te guiar para um caminho de destruição.",
  "O Instituto de Medicina Legal reporta que ele morreu de _____________.",
  "Finalmente, um político que ___________.",
  "Antes de morrer, o meu pai disse-me \"__________\"",
  "_____________. Não reaja como se não gostasse também!",
  "Se pensa que eu _______ então está subestimando as minhas habilidades.",
  "_______ é apenas uma das formas de proteger a nossa juventude",
  "________________",
  "O hobby favorito da Maísa é __________",
  "O GOVERNO ESTÁ MENTINDO: ______ É REAL E ELES ESTÃO ESCONDENDO DEBAIXO DOS NOSSOS OLHOS",
  "Um infeliz acidente com ________ colocou a Juliana Paes no Jornal das 8",
  "Estive acordado até às 5 da manhã pois _________.",
  "___________. É o que digo a todas as minhas vítimas.",
  "_________ é um repelente de mulheres.",
  "Porque é que ninguém me convida para ir a algum encontro?",
  "Talvez o meu tio ainda estivesse vivo se tivesse tentado ______.",
  "Sabe… você até é bastante sexy quando não está fazendo __________.",
  "O livro mais importante de Carlos Drummond de Andrade foi sobre ________",
  "Antes de morrer, ________ vai aparecer diante dos seus olhos.",
  "Na minha próxima pizza, vou adicionar _________ e uma pitada de temperos.",
  "A minha tia maluca não pára de ___________",
  "Na opinião de um amigo, _______ é uma ofensa de pena máxima.",
  "Aposto que a sua vida nunca foi a mesma depois de ___________.",
  "Quem foi o merda que roubou a minha coleção de botons?",
  "A coisa mais romântica que o Bolsonaro fez foi _________",
  "Quando Marx foi para o inferno, Satanás tirou para fora o seu majestoso penis e disse: __________.",
  "Para ser sincero, tem que ter um QI muito elevado para compreender ___________",
  "A tua mãe nunca te disse para ________?",
  "________________",
  "Sorteie 3 cartas. Eu vou escolher uma delas.",
  "Não quero mesmo tocar em ________.",
  "Acho que nenhum de nós aguenta ______",
  "Todos sabemos que José Aldo gostaria de ___________.",
  "_________ é o presente mais estranho que já recebi",
  "O que é mais divertido debaixo de água?",
  "_________ me deixa tão excitado que nem me consigo controlar",
  "O que é que sempre estraga um filme?",
  "Quando ele tirou ________, não sabia o que fazer, portanto comecei a chupar.",
  "O meu carro não tem funcionado bem e penso que o problema seja __________.",
  "Quando a máquina de café estragou, começámos a usar _____ como alternativa.",
  "Se eu fosse preso, o que é que pensariam que eu fiz?",
  "Combaterei o crime com ___________.",
  "Podíamos experimentar _______, mas primeiro temos de nos despir.",
  "Quando era criança sonhava com ________, mas todas as minhas esperanças estão caindo, lentamente, como migalhas.",
  "Provavelmente já vos perguntaram isto, mas o que aconteceria se _________? _________",
  "A última coisa que esperava que caísse do meu rabo era ________, mas aconteceu.",
  "Não tenho uma razão lógica para isso, mas odeio ________.",
  "Qual a pior coisa que Neil Armstrong poderia ter dito quando pisou a Lua pela primeira vez?",
  "Todos nós podemos ser irracionais de vez em quando. Foi por isso que o meu patrão me desculpou por _________",
  "________________",
  "Fomos ao zoológico e vimos ________",
  "A chita pode ser o animal terrestre mais rápido do mundo, mas a pessoa a minha esquerda tem o título mundial de ________",
  "Tem o cuidado de não fazer _________ na casa de outra pessoa.",
  "Qual o sentido da vida?",
  "É difícil responder com ________ na minha boca, professor.",
  "________ é okay ocasionalmente, mas se fizer parte do teu dia a dia, então pode vir a ser um problema.",
  "A minha professora me apanhou com __________.",
  "O meu nome é Miguel, mas a minha família me chama  de \"__________\"",
  "Parabéns! Agora é líder de um culto. A sua religião é ________ e os seus seguidores irão _________ para provar a sua lealdade.",
  "Vi um vídeo onde um homem esticou o seu ânus de tal forma que cabia ________ lá dentro",
  "Combine 3 cartas de modo que façam sentido.",
  "Se ________ fosse do tamanho de um elefante, estaríamos todos na merda.",
  "Eu sempre defendi que ___________",
  "Pior mesmo só se for aquele ____________ do Felipe Neto",
  "O cara adora __________ e se acha o pica das galáxias.",
  "\"HUE HUE HUE\" é uma maneira dos brasileiros dizerem ___________.",
  "Você quebrou o ___________?",
  "A novela Avenida Brasil é melhor que ___________.",
  "Eu vejo ______.",
  "O que Deus disse para o brasileiro?",
  "________________",
  "Que ________ esteja com você",
  "boa notícia é que não é _________. A má é que é ___________.",
  "Eu sou um profissional de ___________",
  "Homem que é homem curte ___________.",
  "Não há nada pior que ser estuprado por __________.",
  "A história conta que Portugal descobriu o Brasil mas a verdade é _________.",
  "Eu uma vez bebi Activia e ___________",
  "___________ prova que Deus existe.",
  "Eu não compro camisinha porque ______.",
  "Saim de perto! Aquilo vai ___________!",
  "É um pássaro? É um avião? Não, é um ____________!",
  "Mãe, _________ caiu!",
  "Amiga, desse jeito eu não tenho como ___________.",
  "Foda-se o dinheiro, eu quero _______.",
  "Bandido bom é __________.",
  "Sugiro que dê ____________ pro seu pai.",
  "Gostei de ___________. Faria de novo.",
  "___________ também se come na China.",
  "Eu adoro o Japão porque posso _______.",
  "Devolve o meu _______, Pedro!",
  "________________",
  "Estou afim de __________ com _________.",
  "As chamadas vieram de _____________",
  "Um bom banho precisa de ____________",
  "Quantas pessoas precisa para __________?",
  "Eu não consigo passar no Enem, e a razão é __________.",
  "Não há nada mais foda que ___________.",
  "Ele se apaixonou por alguém olhando para ________.",
  "O que ajuda Dilma Rousseff a relaxar antes de fazer um discurso?",
  "Novo reality show mostra ___________ fazendo __________.",
  "Adoro atropelar crianças com o meu _________.",
  "Agora é hora de __________.",
  "Notícia de última hora: ___________.",
  "Eu fiz _______ e apareceu um chimpanzé",
  "Porque é que _____________ é uma carta?",
  "Ontem encontrei ___________ à venda no OLX.",
  "O meu estômago estava com desejos de __________.",
  "4 em cada 5 dentistas recomendam ____________.",
  "O que é que o pequeno órfão cego recebeu no natal?",
  "O que eu faria por um KitKat?",
  "__________. HÁ GAAAAAAAAY.",
  "________________",
  "O meu nome é ____________.",
  "____________. Sexy",
  "Nunca tinha pensado em suicídio até ________",
  "Nunca é muito escuro para ____________.",
  "Quem me dera comer _______.",
  "Tudo é melhor que _________.",
  "É perigoso ir sozinho! Leva ___________.",
  "Welcome to the League of ____________.",
  "Booooas pessoal daaqui quem fala é o ____________.",
  "Todos os anos, na terceira terça de Agosto, celebro _____________.",
  "Um estudo científico recente provou que ________ pode causar gravidez.",
  "No início, Deus criou os céus e ___________.",
  "Devia haver um jogo sobre ____________.",
  "Hoje é um bom dia para ____________.",
  "____________? ILLUMINATI!",
  "A minha pequena irmã não pode ser ___________!",
  "A wild ________ appears!",
  "Eu agora identifico o meu género como _____________.",
  "O mundo está acabando, e é tudo devido a ____________.",
  "Imagina um mundo cheio de __________, _________, e de _______. Seria o melhor mundo.",
  "________________",
  "Não tenho um preservativo, mas tenho _____________.",
  "Diz a lenda: se disser _______ três vezes, __________ vai aparecer.",
  "Quero ________ contigo.",
  "Foda-se, me esqueci de ____________ outra vez.",
  "E tudo mudou quando a/o ___________ atacou!",
  "Jesus subiu ao céu e disse _____________.",
  "O recém descoberto 11º mandamento é _____________.",
  "Quando entrei numa reunião neo-nazista vi ___________.",
  "Tenho tanta vergonha de(da/do) ___________.",
  "Pai nosso que estais no céu, _______ seja o Vosso nome.",
  "O novo filme da LEGO terá como tema ___________.",
  "Boa tarde. Esta é a primeira vez que venho a uma reunião deste tipo. Me chamo ______ e sou viciado em ____.",
  "Numa escala de ________ a ________, quão forte é a dor?",
  "A melhor carta vence:",
  "Merda, tenho _______ no meu rabo de novo.",
  "Eu estaria de acordo com a ciência se não fosse ___________.",
  "Não se preocupe senhor, isto é só __________",
  "Porque é que _______ é uma carta?",
  "Se eu fosse uma stripper o meu nome seria ____________.",
  "A minha frase de efeito favorita: ____________.",
  "________________",
  "Mãe, porque é que não posso ____________?",
  "WTF, não precisava  saber que a pessoa a minha direita fez ____________.",
  "Lembram-se daquela noite louca em que __________?",
  "A mais recente inovação no mundo dos brinquedos sexuais é ___________.",
  "A minha parte favorita do teu corpo é ______",
  "As crianças saltaram da cama, desceram as escadas e encontraram ____ debaixo da árvore de natal.",
  "Deveria ser uma prioridade da Humanidade assegurar que ________ nunca acontecerá.",
  "Eu considerava o meu trabalho uma merda até que descobri ____________.",
  "Passei de _________ a __________ graças a ___________!",
  "___________. Palavra do Senhor.",
  "Ligue para 808203203 e participe do sorteio para ganhar um(a) maravilhoso(a)",
  "_____________",
  "Adormeci vendo Altas Horas e quando acordei vi __________ na televisão.",
  "Então Laura Muller, um amigo pediu pra eu te perguntar se __________ é algo comum?",
  "Ontem à noite, um sono de descanso foi arruinado por ___________.",
  "Apesar de ter vergonha em admitir, eu troquei favores sexuais por ____________.",
  "________ ... vergonhoso.",
  "Com grandes poderes vem ____________.",
  "O novo reality show da TVI é sobre ________.",
  "É errado eu querer ter sexo com ________?",
  "CONTACTE O DR. _________ URGENTEMENTE. O PACIENTE ESTÁ EM RISCO DE VIDA",
  "________________",
  "LOL, ________, grande coisa...",
  "Quando fui pescar apanhei ____________.",
  "Encontrei ___________ debaixo da cama da minha avó.",
  "Qual o melhor nome para uma boyband?",
  "O que trará o Neymar de novo para o Santos?",
  "Gostava de _________ com um garoto de 12 anos.",
  "A seguir em casos de família, Ernesto disse: _______.",
  "Quando foi para ________, Rui, de 9 anos, teve que ______ para fazer amigos.",
  "Estranho, o meu/minha ________ cheira a _________.",
  "Nada me descreve melhor que: _____________.",
  "_________: it`s just a prank, disse ________.",
  "O título de tricampeão de levar ________ no cú foi ganho pelo/a ________.",
  "O Renato Russo ouviu ________ a dizendo ________ antes de morrer.",
  "\"Depois não venhas mexer no _______ e na ________ e pedir para ________ comigo\".",
  "\"MOSTRA-ME A TUA ________, QUERO COMER A TUA _______\"",
  "O segredo da Xuxa é ___________.",
  "Cristiano Ronaldo após terminar a sua carreira no futebol decidiu dedicar-se a ____________.",
  "Oh meu Deus, mal posso esperar para experimentar o novo _________",
  "A pizzaria aqui da esquina agora também tem pizza de ________.",
  "No seu próximo vídeo, o Felipe Neto vai ____________.",
  "________________",
  "A tua mãe é mais gorda que ____________",
  "Se Camões visse _________ ele arrancava o segundo olho.",
  "________ é algo que nunca se fala no primeiro encontro",
  "Aquele momento em que percebe que ________ e ________ são a mesma coisa.",
  "Desde que fui apanhado com ________, a minha mãe se recusa falar comigo.",
  "__________ É MENTIRA!",
  "Gosto de roubar _________ de velhinhas.",
  "Uma descoberta recente sobre ________ fez com que começassem a questionar a ciência.",
  "________ é de longe a coisa mais estúpida que existe.",
  "Sou o Vegeta, príncipe de todo ____________!",
  "Por favor senhor, estou pobre e doente e __________!",
  "Não sou estranho, apenas gosto mesmo de __________.",
  "O mundo está acabando, e é tudo devido a ____________",
  "_________? Eu definitivamente fazia sexo com isso.",
  "Acabei de ativar o meu cartão de ____________!",
  "Uma recente onda de piadas começou devido ao início de filmagens de um filme com o nome \"______\".",
  "SOU O ÚNICO QUE EXPERIMENTOU ________?!?!",
  "Me descreva com três cartas",
  "Merda, tenho _______ no meu cu outra vez.",
  "O meu último marido morreu devido a complicações de _________",
  "________________",
  "O único Deus verdadeiro é _____________.",
  "Qual é a senha?",
  "A única maneira de matar Donald Trump é __________.",
  "Eu gostava de _________ com __________.",
  "O que é pior? Comer uma puta com _________, ou __________?",
  "________! Dói, não dói?",
  "Gosto de _____ como gosto do meu café, ____.",
  "Quando pego na sua mão suave e olho para os seus doces olhos, só consigo pensar em _________.",
  "Numa tentativa da Mariazinha ter um namorado, o quê é que ela fez?",
  "Descobriram que o novo hobby do Neymar é ___________",
  "Descobriu-se um álbum inédito do arquivo dos Mamonas Assassinas, seu nome: ________",
  "______! Assim terei abdomens como os do Pogba",
  "No quê é que eu vou gastar os mil reais da minha poupança?",
  "Um estudo recente mostra que os portugueses têm 50% menos sexo depois de serem expostos a _________.",
  "Dica! Quando o seu namorado te pedir para ir lá abaixo, tenta surpreendê-lo com _________",
  "As leis são como as meninas virgens, servem para ser _________.",
  "________ ... outra vez não...",
  "E o prémio do maior pênis vai para _________.",
  "O caminho para o coração de um homem é através de __________",
  "O novo \"Quem quer ser ________\" é muito bom.",
  "________________",
  "Eu sou especial, no outro dia decidi ___________.",
  "Não podes confiar em _______ para ________ porque ___________",
  "Quando tenho coceira no rabo, a melhor opção é _________.",
  "Há um novo método de depilar o rabo. Inclui ________ e __________.",
  "Não penso muito em _______ porque _____ é melhor.",
  "Estou mesmo precisando de __________",
  "Não há melhor sensação na vida do que __________",
  "Descobri a melhor maneira de desentupir o nariz: _______.",
  "Sinceramente, só me falta _________ para ser feliz.",
  "Ela era tão porca que queria _______.",
  "Só porque ela quis _________ não significa que é _______.",
  "Paz mundial? Só preciso de _________ e _________.",
  "Consegui salvar o mundo de _________. Só precisei de _________.",
  "Quais eram os três segredos da Regina Casé?",
  "O meu sonho é ________, mas para isso preciso de _________.",
  "Só há uma coisa pior que ______. ______.",
  "Fiquei desconfortável, nunca tinha visto ________.",
  "Questionei _________ porque ______.",
  "Só consigo atingir o orgasmo se _____________.",
  "Não tenho seguro contra _________. Pensei que não valia a pena",
  "________________",
  "Debaixo do chapéu, Fernando Pessoa levava sempre ______.",
  "Neste mês, a capa da Caras é ___________.",
  "O melhor verso de Renato Russo é, sem dúvida: \"____\".",
  "No próximo carnaval irei vestido de ___________.",
  "________, a verdadeira causa do acidente de Brumadinho",
  "Como a mãe era _______ e o pai era ________, o filho saiu preto",
  "A minha torta favorita é de ___________.",
  "Qual a maior proeza nos jogos?",
  "Todo mundo sabe que _______ é melhor para ________.",
  "Odeio quando as pessoas comparam _____ com _______. Claramente, ______ é melhor que ambos.",
  "Nada mete mais medo do que __________.",
  "________ é o inimigo mais poderoso no jogo.",
  "O que devo esperar na próxima geração de pokémon?",
  "Por favor, junte ao meu clã! Nós adoramos ____________!",
  "________ é o melhor final para __________.",
  "Nenhum jogo de horror é mais assustador do que _________",
  "Nada me deixa mais empolgado para _________ do que _________.",
  "________ é um jogo, não quero saber o que pensa",
  "Durante os descontos da Steam, eu comprei _____ por um preço ridiculamente baixo!",
  "_______ vs _______. Era isso que gostaria de ver.",
  "________________",
  "_______ vai aparecer no próximo ________.",
  "________ é a maior desilusão desta geração",
  "Se não fosse _______, já tinha desistido da vida há muito tempo.",
  "Que lindo _____ tem aí... seria uma pena se alguma coisa acontecesse...",
  "Muitas pessoas consideram ________ legal, mas eu chamo de um monte de merda.",
  "______. É tudo.",
  "Se pudesse, teria sexo com ___ num abrir e fechar de olhos.",
  "_______ é um ótimo conceito para um jogo.",
  "Poucos sabem, mas a verdadeira motivação de Hitler foi tentar conseguir realizar seu sonho de _____",
  "Adoro começar o dia com _____",
  "_______ é a maior escassez em países comunistas",
  "Fazer _______ ajuda muito a conseguir ____",
  "Pra dançar créu tem que ter ______________",
  "Amor é fogo que arde sem se ver; É ferida que dói e não se sente; É um contentamento descontente; É dor que desatina sem ________",
  "Porque eu sei que é amor, sei que cada _____ importa",
  "Por que você não olha pra mim? Me diz o que é que eu tenho de mal.",
  "______? Dúvido",
  "Qual a pior coisa para se conquistar uma mulher?",
  "João amava Teresa que amava _______",
  "Para triplicar seu patrimônio basta investir tudo em ______"
];

const whiteCards = [
  "Se tá na internet é verdade",
  "Aliens.",
  "São Paulo.",
  "Uma morte lenta e dolorosa.",
  "Culpa do PT.",
  "Tentar ir para Portugal para fingir ser rico.",
  "Comer terra.",
  "Alemanha.",
  "Transar com uma cabrita.",
  "Descobrir que estupro não é um nome de um bolo.",
  "Trabalhar honestamente no governo.",
  "Merda, mas muita merda.",
  "Sexo em família.",
  "Boa noite cinderela.",
  "Sexo, drogas e Copa.",
  "Roubar dos pobres e dar para os ricos.",
  "Uma merda mole no canto.",
  "Praias.",
  "Indios.",
  "Funk.",
  "Bater na mulher porque ela não tem pinto.",
  "O menino Neymar.",
  "Sair na rua e não levar um tiro.",
  "Levar um tiro.",
  "Viver no Norte",
  "Primeira Guerra de memes.",
  "Ficar famoso no youtube com minecraft.",
  "A enorme quantidade de brasileiros no japão.",
  "Sexo Oral.",
  "Meu pau.",
  "Igreja Universal.",
  "Pai de família.",
  "Lamber a cabeça de um rato.",
  "Celso Portioli.",
  "Menstruação.",
  "Crianças com câncer anal.",
  "Meu pintinho amarelinho que cabe aqui na minha mão.",
  "PM do Rio.",
  "Lágrimas de crianças.",
  "Argentino",
  "Seu animal imundo",
  "Para nossa alegria.",
  "Cinco reais.",
  "Rolezeira.",
  "Fofão.",
  "Bruna Surfistinha",
  "Muro do Trump",
  "Sujar o azulejo",
  "Perereca suicida.",
  "Um virjão flatulento.",
  "Xingar a sogra.",
  "Boneca inflável.",
  "Bicha muda.",
  "Peidar no elevador.",
  "Tatuar um pênis nas costas.",
  "Sair mijando pelo cu.",
  "Morte cerebral póssexo.",
  "Arroz.",
  "Sapos gays.",
  "Humor negro",
  "Taxistas.",
  "Café.",
  "A série Super Campeões.",
  "Uma porta.",
  "Um lápis.",
  "Um lenço de papel sujo.",
  "Liberais.",
  "Testemunha de Jeová.",
  "Um bode zangado",
  "Os mamilos do traje do Batman.",
  "Lactação masculina.",
  "Um amante latino.",
  "Um amante ibérico.",
  "O gigantesco par de bolas do Papai Noel.",
  "Sonhos eróticos com o Papa Francisco.",
  "Dançar lambada.",
  "A perna amputada da minha avó.",
  "Um padre.",
  "Fé em Hitler.",
  "Uma boa dose de anal.",
  "A perda da virgindade.",
  "Um autista.",
  "Desisto, cartas de merda.",
  "Pequenas vaginas voadoras.",
  "Abusar de crianças brasileiras.",
  "Câncer terminal.",
  "Um negro nazista.",
  "Sexo com animais em extinção.",
  "Massacre escolar.",
  "O meu primeiro assassinato.",
  "Escassez de comida.",
  "Supertrunfo.",
  "A carta certa pra hora certa.",
  "Supremacia nordestina.",
  "Queijo quente.",
  "Um homem maléfico com roupas maléficas.",
  "Dançar com uma vassoura.",
  "Hipsters.",
  "Guerreiros sociais",
  "Ser raptado pelo Peter Pan.",
  "Boa gramática.",
  "Humilhação sexual.",
  "O ouro que Portugal roubou.",
  "Um kit de vasectomia caseira.",
  "Se declarar um jihad.",
  "Chicotear um escravo desobediente.",
  "Vibrador de próstata",
  "O vibrador da minha mãe.",
  "Tomar banho numa torradeira gigante.",
  "Supremacistas brancas que se recusam a comer os M&Ms castanhos.",
  "Violar um cego para ele não saber quem foi.",
  "Comer bebés com microcefalia.",
  "Paralisia infantil.",
  "Saber que a filha virou feminazi.",
  "Porno de anões.",
  "Irritar um fã de anime gordo.",
  "Ninja das favelas.",
  "Por o pau pra fora.",
  "Uns drogados procurando pokémons.",
  "Bacalhau.",
  "UBER.",
  "Um trompete",
  "Um isqueiro sem gás.",
  "Inserir um copo no meu ânus.",
  "A merda do buraco gigante da camada de ozono.",
  "Controle total da comunicação social.",
  "Galvão Bueno narrando a vida sexual dos rinocerontes.",
  "Bochechar esperma antes de deitar.",
  "Comer uma banana sugestivamente.",
  "Gritar DINHEIRO para chamar a atenção de um judeu.",
  "Órfãos congelados com órgãos de alta qualidade.",
  "Chupar sedutoramente um pirulito.",
  "Pornografia de amputados",
  "Furar preservativos.",
  "Gêmeos siameses que se odeiam.",
  "Pés.",
  "Dançar com um idoso tão idoso que os testículos parecem bolas de ping pong.",
  "Diabetes.",
  "Uma freira.",
  "Uma cabra sendo violada por um cão de guarda.",
  "Falta de bolas.",
  "Aquela peguete do outro dia.",
  "Um preto chapado.",
  "O vídeo da orgia do João Dória.",
  "Deixar a sua avó passar uma noite com o estuprador de velhinhas.",
  "Nada que o Hitler não tenha feito.",
  "Quantidades industriais de sêmen.",
  "Os filhos do embaixador iraquiano.",
  "Porta dos fundos.",
  "Um cavalo relinchando.",
  "Bíblia satânica",
  "Força de mil sóis.",
  "Masturbação anual coletiva de padres e bispos.",
  "Uma piscina cheia de corpos.",
  "Violação de todos os direitos básicos do ser humano.",
  "Chuva de pirocas flamejantes.",
  "Abusar de crianças africanas.",
  "Sangue de menstruação.",
  "Um balão feito de preservativos usados.",
  "Abuso infantil apenas por diversão.",
  "Destruir as provas.",
  "Acariciar",
  "Guia de sobrevivência para o holocausto branco.",
  "Clínica de aborto clandestina dos católicos.",
  "Introdução ao canibalismo.",
  "Nádegas firmes.",
  "Obesidade mórbida.",
  "Síndrome de Estocolmo",
  "Funcionários do serviço de atendimento ao cliente.",
  "Os administradores gordos e preguiçosos do Brasil.",
  "Pintar com os dedos",
  "Uma pistola de água cheia de urina de cão.",
  "Retardados.",
  "Cavalheirismo.",
  "Uma vagina coberta de sangue.",
  "Um homem gordo careca da internet.",
  "Um baixo padrão de vida.",
  "Bater na esposa",
  "Ser um adulto ocupado com muitas coisas importantes para fazer.",
  "Fabricação de estatísticas.",
  "Soldados geneticamente modificados.",
  "Ter um penis.",
  "Só a cabecinha.",
  "Rasgar o peito de um homem e tirar o seu coração enquanto ainda bate.",
  "Cócegas no escroto.",
  "Humilhação sexual.",
  "Uma orgia com os ministros.",
  "Crianças não vacinadas que acabam sendo autistas do mesmo modo.",
  "Procurar por um talento pornográfico numa festa de graduação do secundário.",
  "Não deixar um cromossomo extra nos deixar pra baixo.",
  "Fazer um 69 numa idosa com 96 anos.",
  "Um kit de vasectomia caseira.",
  "Um cavalo com um micropênis.",
  "Um sobrevivente de um aborto.",
  "Um sonho erótico com a Jojo Todinho.",
  "Noite de bingo na igreja de Satanás",
  "Freiras com armas.",
  "Sexo num banheiro público.",
  "Jesus deixar uma criança morrer porque a foto só teve 997 likes.",
  "Raptar 24 alunos do ensino básico para organizar os meus próprios jogos mortais.",
  "A arte de chicotear alejados.",
  "Tentar adivinhar a data da morte das crianças com câncer.",
  "Ver um vídeo porno no celular durante uma viagem de metrô.",
  "Vomitar durante o sexo oral.",
  "Uma freira se masturbardo com um crucifixo.",
  "Bater em órfãos porque ninguém vai contar aos pais deles.",
  "Penetração dupla",
  "Usar as genitais do inimigo como troféu.",
  "Fazer sexo com a própria filha.",
  "Uma parede de dinheiro",
  "Torturar fetos abortados.",
  "Uma mãe solteira.",
  "Masturbar-se ao ponto do penis mudar de cor.",
  "Furar a orelha usando uma agulha com tétano.",
  "Um socialista usando um iPhone.",
  "Masturbar um mendigo.",
  "Fazer uma lavagem intestinal com coca-cola.",
  "Bater uma ao lado da irmã enquanto ela dorme.",
  "Masturbar com o som dos pais fazendo sexo",
  "Adotar um chinês com trombose.",
  "Disparar uma metralhadora numa escola cheia de crianças.",
  "Um celular que é mais inteligente do que o utiliza.",
  "Putas e vinho verde.",
  "Porno de anões amputados.",
  "Atacar a mãe por ser um adolescente com problemas",
  "Descoberta do Brasil.",
  "Um alface da horta da sua avó.",
  "Um penis caindo de podre.",
  "Vizinhos tendo sexo a meio da noite.",
  "Ter a primeira experiência sexual com um galo.",
  "A tua mãe de quatro.",
  "Suor debaixo das mamas.",
  "Um balde com 50 litros de lubrificante.",
  "Gozar na pia",
  "Cagar no mictório",
  "Um policial comendo um iogurte",
  "Infectar velhos com gripe.",
  "A garagem da vizinha.",
  "Jogar futebol na escola e não convidar o gordo da sua turma.",
  "Alucinações.",
  "Esconder a minha herpes com pelos púbicos gigantes.",
  "Uma câmara de gás.",
  "Ouvir discursos inspiradores",
  "Chuva ácida derretendo a pele dos ossos.",
  "Um corpo mutilado",
  "Coreografia terrível.",
  "Ter um caso com a psicóloga.",
  "Chantagear.",
  "Morrer de cancer do pulmão",
  "A ciência das ereções",
  "A comunidade muçulmana.",
  "Ter um tumor cerebral do tamanho de uma melancia.",
  "Usar Auschwitz como bode expiatório.",
  "Democracia.",
  "Monarquia",
  "Uma centopeia humana.",
  "Violência doméstica",
  "Injetar heroína.",
  "Ajudar pessoas.",
  "Uma privada que fala",
  "Fazer sexo com a esposa no escuro, e ao acordar descobrir que era o seu cão.",
  "Tornar-se pai porque ela se esqueceu da pílula do dia seguinte.",
  "O restaurante casa de grelhados do Hitler.",
  "Fazer clones de mim mesmo para usar como alibi.",
  "Ser enterrado vivo.",
  "O presidente da república.",
  "Olhar para a barba de um homem e reparar que tem esperma.",
  "Zumbis.",
  "Uma desculpa formal.",
  "Animais gays.",
  "Negar algo mesmo quando há provas em vídeo.",
  "Encontrar alguém durante um show.",
  "Encontrar uma ex numa casa de swing.",
  "Aquele amigo \"especial\".",
  "Dizer que tem alergia a glúten.",
  "Usar a irmã como colete a prova de balas",
  "Pessoas chinesas.",
  "Pansexuais.",
  "Bissexuais.",
  "Dizer coisas porcas em linguagem gestual.",
  "Um africano albino.",
  "O que os homens fazem para passar tempo na prisão.",
  "Esquecer-se de ser bonzinho.",
  "Cuecas mágicas",
  "Fazer revisões para um teste que considera inútil.",
  "Escorregar e acidentalmente penetrá-la.",
  "Adolescentes excitados ejaculando em todo lugar.",
  "Estudar.",
  "Escrever uma canção de amor.",
  "Um brasileiro",
  "Um angolano.",
  "Chegar à conclusão que é um merda.",
  "Ter que reutilizar um preservativo.",
  "Uma corrida mortal de cadeiras de rodas.",
  "Síndrome de Down.",
  "Um jogo muito curto de Roleta Russa.",
  "Um feiticeiro.",
  "Ficar sem erva e usar palha como substituto.",
  "Parkour",
  "Química.",
  "Descobrir que é alérgico a látex da pior maneira.",
  "Wi-Fi terrível",
  "O comércio de escravos.",
  "Tiroteio em massa",
  "A produção em massa de corpos para o mercado negro.",
  "Os bons velhos tempos.",
  "Ganhar algo na vida.",
  "Fazer um boquete em um morto.",
  "O filho gay de um militante do MBL.",
  "Zoofilia.",
  "Envenenar todos os membros da família.",
  "Ser preso por disparar acidentalmente na namorada pela porta do banheiro.",
  "Morrer por dentro.",
  "Um coma.",
  "Enviar um nude para a pessoa errada.",
  "Um bebê feio.",
  "Sabor energético",
  "Um anão fazendo striptease.",
  "Um tatuador cego.",
  "Uma posição do Kama Sutra.",
  "Não ter wifi.",
  "Usar a janela anônima para navegar na internet.",
  "Espermicidio.",
  "Gays homofóbicos.",
  "Flashbacks da guerra do Paraguai.",
  "Um tamagotchi.",
  "Os filhos da revolução.",
  "Começar uma revolução.",
  "Dizer adeus.",
  "Cena de porno lésbica em que ambas as atrizes já foram homens.",
  "Crianças autistas",
  "Fingir um orgasmo para ser simpático.",
  "Compensar por algo.",
  "Uma sala cheia com as minhas ex-namoradas.",
  "Injeção letal.",
  "Encontrar uma minhoca na sua maçã.",
  "Querer o que é melhor para todos.",
  "Incesto acidental.",
  "Fazer cocô numa vagina.",
  "Uma viagem de barco gratuita para o inferno.",
  "Um monge sem roupa",
  "Mijar durante o banho.",
  "Mamilos gigantes.",
  "Jogar água em mendigos.",
  "Aprender uma nova língua",
  "Hálito de prostituta.",
  "Envenenar a ex-mulher.",
  "O lado bom da vida.",
  "Ser muito inocente para este jogo.",
  "A crise de refugiados.",
  "Tensão sexual na reunião familiar.",
  "Tomar banho no sangue de bebés recém nascidos.",
  "Exorcismo.",
  "Exorcismo mal sucedido.",
  "Boas intenções",
  "Chineses chorando porque vão comer o seu cão ao almoço.",
  "Uma mulher muçulmana sendo espancada pelo marido por ter mostrado o tornozelo.",
  "Fisiculturistas.",
  "Um padre Católico",
  "Trabalho infantil.",
  "Bar gay",
  "O início do fim.",
  "Aquele pedaço de papel higiénico que fica preso no seu rabo.",
  "Tornar virgens em não virgens mesmo após dizerem que não.",
  "Cometer suicídio.",
  "Eclipse lunar.",
  "Biologia",
  "Usar um anão como bola.",
  "Raça ariana.",
  "Comprar novos brinquedos sexuais.",
  "Virgindade anal.",
  "Rir excessivamente da minha própria piada.",
  "Jogar xadrez.",
  "Casar para ter poder ter sexo",
  "Uma garota que chama um virgem pra sair só pra ele pensar que vai perder o cabaço.",
  "Esconder câmeras no quarto da minha namorada.",
  "Ler histórias eróticas em braille",
  "Chegar finalmente à Europa após dias de viagem desde a Síria",
  "Um judeu sentir cheiro de gás durante um banho.",
  "Ter a atitude errada.",
  "Fazer sexo num elevador porque está preso há muito tempo.",
  "Uma escova de dentes com pelos pubianos.",
  "Falar consigo mesmo",
  "Uma fábrica de corpos.",
  "Usar tanto viagra que o penis explode.",
  "Falhar num suicídio.",
  "Esperma suicida.",
  "Colher e comer os órgãos de sem abrigos.",
  "O penis da sua mãe no meu cu.",
  "Descobrir que é alérgico a sémen tarde de mais.",
  "Roubar pombos.",
  "Curtir com a irmã gêmea da namorada sem saber",
  "Masturbar-se a ver imagens de Salazar",
  "Masturbar-se a ver imagens de Angola.",
  "Mandar acidentalmente uma mensagem sexy à minha avó.",
  "O som de crianças gritando.",
  "Chegar à conclusão que sou o pior homem bomba de sempre.",
  "Bigode de taxista.",
  "Ser ateu graças a Deus.",
  "A virgindade de um rapaz.",
  "Ter o mamilo esquerdo maior que os outros dois.",
  "Um polvo que adivinha o resultado de jogos de futebol.",
  "Pênalti pro corinthians!",
  "Palmeiras não tem mundial",
  "Um são paulino que não seja gay",
  "Não conseguir achar um santista com menos de 60 anos",
  "Uma prostituta virgem.",
  "Uma freira grávida.",
  "Uma macumba.",
  "Conduzir um caminhão na direção de um mercado no Natal.",
  "Um plano para destruir a Terra.",
  "Stalkear o Facebook de uma garota.",
  "Uma garrafa de urina fresca.",
  "Pessoas altas.",
  "Um cadáver mais sexy que a sua esposa.",
  "Culpar os idosos",
  "Prostitutas do OLX.",
  "Castrar anões.",
  "A Ira de Deus.",
  "Ativo a minha carta armadilha: Chuva de Pirocas!",
  "Quando se descobre que quem descobriu a América foi a Pocahontas.",
  "Capitão Cueca",
  "Capitão Hipoglós",
  "Masturbar um cavalo.",
  "Preservativos com doenças sexuais",
  "Gritar versículos da Bíblia durante o sexo",
  "A CIA estar espionando esta sala neste momento e achar tudo ofensivo.",
  "Ficar com o penis preso em arame farpado.",
  "Nascer gay",
  "A saborosa vagina da minha tia.",
  "Receber conselhos da comunidade local de BDSM.",
  "Tentar decidir onde esconder o corpo da minha avó morta.",
  "Um boquete feito por uma piranha.",
  "Fazer uma maratona de 24 horas de pornografia pesada.",
  "Preservativos com sabores variados.",
  "Atirar uma granada de luz para um hospital cheio de epiléticos.",
  "Afogar-se numa piscina cheia de esperma.",
  "Usar as cuecas com sangue da menstruação sua irmã.",
  "Roubar um caminhão lotado de meninas virgens.",
  "Bater na parte gay do teu filho bisexual.",
  "A cabeça de uma cabra.",
  "As profundezas do inferno.",
  "Rir durante uma notícia de estupro.",
  "Fazer um boquete ao professor para aumentar a nota.",
  "Um mulalato nu no topo de um piano feito de ouro.",
  "Uma bomba de sexo explodindo nas suas calças.",
  "Uma jaula cheia de adolescentes na puberdade.",
  "Entrar no quarto do seu pai enquanto ele vê hentai.",
  "Masturbar-se enquanto a vovó observa.",
  "Um detector de ereções",
  "A sensação que tem nos testículos quando está vendo Titanic.",
  "Uma meia com esperma seco.",
  "Ouvir a história do seu avô negro de como escapou da fazenda do seu dono",
  "Uma montagem de decapitações da ISIS.",
  "Um quarto cheio de cabeças de gato decapitadas.",
  "Um garoto branco com raiva pela sua escola, portando com uma glock.",
  "O cheiro de infiéis queimando.",
  "Fazer linguagem gestual para explicar música pra sua mãe surda.",
  "A parte do teu cú que está sempre úmida.",
  "Masturbar-se vendo os filmes da disney.",
  "Obrigar crianças com síndrome de down a fazer duelos.",
  "Uma orgia incestuosa.",
  "Melancia frita.",
  "O cartel de droga colombiano.",
  "Jesus Cristo, Rei dos Judeus, destruidor de vaginas.",
  "Entrar na lista de malvados do Pai Noel de propósito.",
  "Um lança chamas com defeito de fábrica.",
  "Dormir de forma erótica.",
  "Pedir cigarros ao professor de educação física.",
  "A tensão sexual de olhar para os lóbulos das orelhas de alguém.",
  "A minha doce virgindade.",
  "Jogar tabaco para crianças africanas cheias com fome.",
  "Trocar os bilhetes do campo de férias com os do campo de concentração.",
  "Odeio minorias.",
  "Tabaco",
  "Xibiu",
  "Tabaca",
  "Fazer uma apresentação com uma ereção.",
  "Um ringue sexual de virgens.",
  "Comer um garoto obeso de 10 anos.",
  "Injetar uma dose letal de memes na tua corrente sanguínea.",
  "Usar fio dental na sua vagina.",
  "Um exército de brinquedos sexuais estragados.",
  "Violar um bebé com um garfo.",
  "Uma vagina de strapon.",
  "Querer molestar criancinhas no metrô",
  "Uma boneca sexual suja",
  "Apanhar uma doença sexual por fazer sexo no oceano.",
  "Uma sensação de ardor",
  "Fazer sexo apenas quando tem aranhas a andando pelo seu corpo.",
  "O meu super sexy micro penis.",
  "Um bong cheio de urina.",
  "Mijar em crianças.",
  "Ir ao zoo e reparar que o penis de um chimpanzé é maior que o teu.",
  "Os beijos molhados da avó.",
  "Barulhos estranhos de cavalo vindos do quarto dos teus pais.",
  "Mijar como um gatinho mau.",
  "Fazer sexo em público com o propósito de ser apanhado.",
  "Congelar o seu mijo na forma de um dildo e obrigar uma mulher a chupá-lo.",
  "Usar aleijados para demonstrar o efeito dominó",
  "Fazer sexo enquanto está ao lado dos seus pais.",
  "Um boquete tão bom que congela o tempo.",
  "Um pelo pubiano encravado.",
  "Terminar com a namorada por falta de sexo.",
  "Ser enrabado numa mesa de bilhar.",
  "Ser asfixiado durante o sexo.",
  "Um homem com dois penis",
  "Escândalos sexuais de professores.",
  "Um dedo em todos os buracos.",
  "Um saleiro cheio de pó de Judeus.",
  "Qualquer coisa com um buraco.",
  "Ser tocado pelo Papa num lugar que não devia.",
  "Ser amamentado pela sua namorada.",
  "Acreditar que o meu pênis é a minha filha e pedir para crianças brincarem com ela.",
  "Mandar fotos do meu pênis enquanto ela está com a sua família.",
  "Jogar o meu bebé feio fora.",
  "O pênis grande do meu namorado.",
  "Jogar twister com amputados.",
  "1 litro de mijo.",
  "Meter os dedos no proprio cu.",
  "Bolhas de esperma.",
  "Cem flexões com o penis.",
  "como se masturbar.",
  "Estuprar alguém pelo celular.",
  "Ligar para o namorado só para ele te ouvir tendo um orgasmo.",
  "Fazer o seu parceiro comer comida em cima do teu corpo, e vomitar depois em cima de ti.",
  "Sucos vaginais",
  "Foder ao vivo na televisão nacional.",
  "Peidar no cinema e culpar os órfãos.",
  "Acidentalmente engravidar a sua filha",
  "Fazer cocô com a porta aberta.",
  "Um dildo de vidro de 16 centímetros quebrar dentro do seu ânus.",
  "Um saco de diarreia",
  "Silenciar a sua namorada com o teu penis.",
  "O papai vendo as minhas cuequinhas para saber se estão molhadas",
  "Uma linda vista numa praia de nudistas",
  "Um jarro cheio de sangue de menstruação.",
  "Fazer sexo oral numa mulher menstruada.",
  "Masturbar-me tão depressa que começa a pegar fogo.",
  "Lamber o meu rabo coberto de mijo.",
  "Fazer sexo anal para que Jesus não me odiar.",
  "Mandar uma foto do seu pau para a sua mãe acidentalmente... e receber outra de volta.",
  "Ser violado pelo monstro de baixo da cama.",
  "Ir para a friendzone de uma prostituta.",
  "Masturbar ao contrário de forma a ejacular na sua cara.",
  "Dizer para as pessoas que é Azteca e sacrificar a própria irmã.",
  "Receber uma foto de um penis que era destinado para a sua namorada",
  "Ser assediado sexualmente por uma criança de 10 anos.",
  "Chamar Auschwitz  de \"Jurassic Park\".",
  "O lado estranho do Pornhub.",
  "Vender a sua alma no OLX.",
  "Ser alérgico a gays",
  "Preservativos vendidos exclusivamente para gays.",
  "Conduzir uma carrocinha cheia de explosivos contra um orfanato.",
  "Usar preservativos recicláveis.",
  "Chicotear a namorada por ela ter um amigo negro e chicotear o amigo depois.",
  "Pensar que a Lista de Schindler é um site online para comprar e vender Judeus.",
  "Clicar acidentalmente no botão de Partilhar no Facebook num vídeo porno.",
  "Usar água benta como lubrificante.",
  "Colocar um amputado numa escada rolante.",
  "Ter os órgãos sugados pelo cu.",
  "Jogar a bolinha para um feto apanhar",
  "Uma loja de armas ao lado da Ri Happy.",
  "Um pênis mutilado.",
  "Citar o Fernando Pessoa depois de fazer sexo.",
  "Descobrir que a garota com quem tem saído é uma agente infiltrada da PM",
  "Ter uma ereção durante \"A Paixão de Cristo\".",
  "Um bissexual homofóbico.",
  "Não ser o pai favorito.",
  "Projéteis de vômito.",
  "Encontrar o seu pênis pela primeira vez",
  "A outra família do papai.",
  "Descobrir piadas de peidos.",
  "Dar um murro na enfermeira durante o parto.",
  "Fingir que não notou o cheiro da fralda.",
  "Acidentalmente usar leite materno no café",
  "Colocar uma coleira no teu filho.",
  "Ser uma cabra com a idade de 5 anos",
  "Fumar durante a gravidez.",
  "Descobrir que é adotado durante uma aula de Biologia do 8º ano.",
  "Os ciganos do centro.",
  "Limpar o cu antes de cagar.",
  "Que informação dramática.",
  "O ator Tommy Lee Holla",
  "A antiga arte de luta portuguesa, o Manejo do Pau.",
  "Vender um par de sapatos do pé direito",
  "Estou cheio de te ouvir.",
  "Comprar droga com caixas automáticos.",
  "Uma granada militar",
  "Abelha rainha",
  "Fui adotado pela Igreja Universal do Reino de Deus",
  "Culpar a esquerda por todo o mal.",
  "A DIREITA É QUE É A CULPADA.",
  "O dinheiro perdido do Banco Central.",
  "Chamar os países africanos de países de merda.",
  "Ir à máquina da verdade",
  "Saber a música de introdução do Dragon Ball toda.",
  "1001 maneiras de fazer miojo.",
  "Dar um mês de vida a um bebê recém nascido",
  "Espíritos que se auto masturbam.",
  "Herege",
  "Confundir ENEM com Eminem.",
  "Os peitinhos da cabritinha.",
  "Encontrar uma lagarta no meu caldo verde.",
  "Um belo chouriço.",
  "Uma maravilhosa farinheira",
  "Aquela menina que está na janela.",
  "Pagode, feijoada e sexo",
  "O beck nosso de cada.",
  "Cavaleiros da Ordem de Cristo.",
  "O carro desaparecido do Governo de Espírito Santo.",
  "Uma mulher durona, que não atura merdas de pessoas",
  "Barroco.",
  "Uma batalha pela alma da nossa nação.",
  "Uma barriga cheia de cerveja Skol.",
  "Um bebê mais resistente à água.",
  "Um preto à prova de bala.",
  "Um grupo de bastardos irritados.",
  "Um grupo de palavras científicas juntas para explicar algo que não compreendo.",
  "Comprar pizzas de marca branca.",
  "Pizza de strogonoff",
  "Chorar como uma criancinha pequena.",
  "Dormir com a bunda quente",
  "A fina linha entre erótico e psicótico.",
  "Doces reciclados.",
  "Tornar-se policial para atirar em pretos como esporte.",
  "Uma orgia de lenhadores.",
  "Almoçar enquanto se faz cocô",
  "Um ônibus cheio de brancos.",
  "Privilégio branco.",
  "Um cartão de Natal sem dinheiro.",
  "A pessoa preta mais branca que conhece",
  "Engravidar na Espanha, na viagem de final de ano",
  "Ninjas cearenses que usam crocs.",
  "O cheiro de ciganos",
  "O Acre",
  "Mandar merda para as pessoas pelo correio",
  "Ser violado por um grupo de pequenos rapazinhos",
  "Crianças tendo ataques de asma.",
  "Estou desapontado com a pergunta desta rodada.",
  "Genocídio branco.",
  "Substituir a insulina de um diabético por glucose.",
  "Um empregado do McDonald's feliz.",
  "Teletubbies tomando banho com os seus .",
  "Um punho cheio de cinzas de Judeus",
  "Onde as putas vão para morrer.",
  "Meninas de 12 anos que parecem ter 18.",
  "Converter-se ao Islão no meio de um voo.",
  "Um buraco da glória com uma tartaruga no outro lado.",
  "Uma massagem na próstata.",
  "Crianças cobertas por provas de DNA.",
  "Injeção de vinho tinto na veia.",
  "Comer frango frito e usar a gordura como lubrificante",
  "Colocar gatinhos numa trituradora.",
  "Distrair amigos japoneses com problemas difíceis de matemática",
  "Pedir emprestado o rim de alguém",
  "Fazer crianças chorarem por diversão e dinheiro",
  "Usar um hospital como fonte de entretenimento",
  "Masturbar até começar a sair sangue",
  "Ouvidos com pêlo em excesso",
  "Ser tão vegano ao ponto que só come a sua própria semente",
  "Usar crianças para bater em outras crianças",
  "Um jarro cheio de preservativos usados",
  "Usar frango frito como uma distração na cracolândia",
  "O último homem branco da África",
  "Fazer a sua namorada gemer bem alto para fazer inveja no seu pai",
  "Crianças autistas caindo",
  "Apostar o almoço dos filhos no cassino",
  "Fazer uma transfusão de sangue num bairro gay.",
  "Viver a vida de pobre",
  "Conduzir uma mulher cega ao seu porão em vez da casa dela",
  "Um pedófilo de patins",
  "Usar preservativos que brilham como sabres de luz",
  "Masturbar para uma foto da sua mãe quando ela tinha 18 anos",
  "Um brasileiro nunca desiste!",
  "O espírito está disposto, mas a carne está esponjosa e ferida",
  "Meninas do interior que colocam nudes no twitter.",
  "Pensar que a parte azul da borracha apaga caneta",
  "Preferir Digimon a Pokémon.",
  "Desejar que nunca tivesse profanado o cemitério cigano",
  "Ser um participante passivo na minha própria vida.",
  "Usar a minha religião como guia moral contra todos",
  "Cheio de arrependimento.",
  "Estar morto por dentro",
  "Cobrir a casa com alumínio para se proteger do governo.",
  "Morrer durante o sono.",
  "Teorias de conspiração sobre répteis.",
  "O melhor jogador do mundo de bocha.",
  "Chutar crianças",
  "Pedir pro filho acender o seu cigarro no fogão",
  "Usar o \"Era uma vez... o corpo humano\" como material de masturbação",
  "Comprar kinder ovos só para ficar com o brinde.",
  "A única cultura que possuo são bactérias",
  "Um bigode bem aparado",
  "A sua dependência de álcool estar destruindo a sua família",
  "O cansaço do dia a dia",
  "Os aviões que liberam agentes químicos controlando o tempo",
  "Chorar até adormecer",
  "Procurar conforto em memes",
  "Autismo funcional.",
  "Chegar à conclusão que a morte é inevitável e não há sentido na vida.",
  "Voltar no tempo para convencer a sua mãe a não engravidar",
  "Diabetes tipo 2.",
  "Diabetes tipo 1",
  "Aceitar que é uma perda de espaço e vida",
  "Aceitar o fato que a NASA já teve contato com vida extraterrestre",
  "Estar sempre procurando aprovação das pessoas que te rodeiam",
  "Torturar-se com ansiedade por coisas que não valem a pena",
  "Ter uma ereção ao mínimo toque",
  "Ficar com o pênis preso",
  "O resultado da desigualdade de salários.",
  "Pedir asilo na favela da rocinha.",
  "Ser atacado por um beija-flor",
  "Um dildo que também é usado como termômetro",
  "Rodar um fidget spinner na cabeça do meu pênis",
  "As escolhas de merda da sua vida",
  "Uma cara tão feia que conta como anal",
  "Meter lixo radioativo na minha vagina até parir um super herói.",
  "Imigrantes de países de merda.",
  "Aumentar o seu penis com os produtos do Boticário",
  "Usar o seu diagnóstico de câncer como desculpa para ser um corno",
  "Ser um corno manso",
  "Ser o pika das galáxias",
  "Uma vida perfeita arruinada por uma criança.",
  "Cometer suicídio para evitar exames",
  "Fumar a quantidade de erva que os executivos da SIC fumaram para aceitarem a Supernanny",
  "Imprimir um dildo anal na minha nova impressora 3D.",
  "Uma referência estúpida da internet que já não é mais engraçada.",
  "Retirar asas às borboletas para elas se tornarem lagartas de novo",
  "Urinar na vagina de uma mulher.",
  "Um erro de proporções bíblicas.",
  "Rio de Janeiro",
  "Ouro Preto",
  "O nordeste",
  "A polícia do Espírito Santo",
  "Discutir com um empregado autista do banco",
  "Esfregar os seus testículos na parede",
  "Enfiar goela abaixo",
  "Salvar um edifício de um bebé em chamas.",
  "A sua mãe paraplégica.",
  "O orgulho da Anitta.",
  "Sons estranhos.",
  "Uma esperança no impossível e um medo do inevitável",
  "Os restos de esperança do seu pai sobre o seu futuro",
  "Fumar o meu peso em erva.",
  "Aprender o teu lugar neste universo frio e sem sentimentos",
  "Dirigir numa rua sem saída, mas não parar.",
  "Pensar se é mais absurdo suicidar-me ou continuar a viver.",
  "Lamber até ficar limpo.",
  "Beijo grego",
  "Lamber um cú todo melado",
  "A sua mãe não te ama.",
  "A sua família gritar para sair de uma coma, que já tem há 10 anos",
  "A diminuição de uma população causada por canibalismo",
  "A opinião de pessoas nascidas milhares de anos antes do nosso tempo.",
  "Fantasiar sobre uma vida que nunca irá ter",
  "Entusiasmar-me pelo dia seguinte quando eu sei que a única coisa que me espera é sofrimento eterno",
  "Descobrir que teus comprimidos são na verdade placebo.",
  "Um dos mamilos mais perigosos do mundo",
  "Flashbacks do tempo que era um escoteiro.",
  "Vestir a sua pele",
  "Tecnicamente não é um crime.",
  "Reprogramar o teu cérebro para o tornar mais suscetível à nossa propaganda",
  "Plantar falsas memórias no cérebro das crianças de um orfanato.",
  "Fugir para ir viver com as pessoas da floresta.",
  "A fonte principal da humilhação do teu pai",
  "Esta simulação que criámos e que confundes com a realidade.",
  "Machado de Assis",
  "Cheirar cocaína do rabo de uma prostituta",
  "Vai à merda",
  "Ser fodido no rabo pela minha namorada.",
  "Amanteigar o meu ânus e enfiar uma baguete quentinha.",
  "Dar-lhe uma chapada com o meu penis",
  "Cortar um pedófilo ao meio com uma motosserra.",
  "O monitor mais sensual do campo de férias para gordos.",
  "O meu ânus é uma autoestrada.",
  "O sexo mais primitivo.",
  "Não ser um assassino em série.",
  "Ser uma pessoa terrível só para poder fazer um sexo selvagem com o Satanás",
  "O vazio onde o meu coração devia estar.",
  "Orgias de robôs",
  "Estar coberto de aranhas e gritar enquanto rastejam pela tua garganta abaixo",
  "Provavelmente comido por tubarões.",
  "Esquecer daquele homem que raptou até que o porta-malas começa a cheirar mal",
  "Ejacular enquanto falamos",
  "Os barulhos vindos do inferno que todos os frigoríficos fazem durante a noite",
  "Usar o meu tempo livre para \"outras coisas\"",
  "Canibalizar a sua irmã.",
  "Drogas que nem sequer ouvi falar",
  "Lamber as cartas da Avó por ela",
  "Numa espiral decrescente facilitada por desemprego e drogas.",
  "Sou uma máquina de cocô",
  "A tecnologia extraterrestre esperando ser descoberta no fundo do Tietê",
  "Provar para as mulheres que é um rapaz simpático ao segui-las num parque de estacionamento enquanto esfrega a sua ereção.",
  "Pagar 10000 reais ao seu médico para te colocar de volta num coma.",
  "Ter uma festa de limões com os teus avós",
  "Uma metralhadora que dispara pastéis",
  "Uma fotografia do interior da minha cavidade anal",
  "Essencialmente inútil.",
  "O supercomputador que está nos controlando.",
  "Provavelmente nada",
  "Trabalhar durante 60 anos e rezar para não morrer de ataque cardíaco até lá",
  "Esquecer de estimular a minha próstata",
  "O cachorro mais estiloso do Brasil",
  "Obliterar a Venezuela de uma vez por todas.",
  "Um crocodilo com mamilos de borracha em vez de dentes.",
  "Masturbar um ao outro, por contato visual.",
  "Enfiar o seu dedo no seu umbigo e cheirar",
  "Pensar nos parasitas que vivem nas minhas sobrancelhas.",
  "Conhecer seres extradimensionais e sem querer destruir o portal deles.",
  "Uma rádio que toca pessoas gritando em vez de músicas.",
  "Uma máquina sexual que está banida em 57 países desde 2014",
  "Gostar de K-POP",
  "Fumar tanta erva que começa a ficar genuinamente preocupado com os sentimentos das outras pessoas",
  "Apanhar a primeira folha de outono na sua língua",
  "Investigar a sua linhagem e descobrir que na verdade é colombiano.",
  "Pensar se é gay enquanto chupa o pinto do seu melhor amigo",
  "Chicotear o seu escravo sexual até começar a se portar bem.",
  "Crosta de sémen.",
  "O teu desempenho sexual medíocre",
  "Diarreia.",
  "Comer uma banana.",
  "Gonorreia.",
  "Um bebé morto",
  "Disparar palitos através do penis.",
  "Cometer genocídio.",
  "A conta do gás do Hitler.",
  "Sexo.",
  "Pornografia infantil.",
  "Merda.",
  "Mijo",
  "Uma vagina com dentes.",
  "Queijo derretido.",
  "Ser apanhado com um rapaz de 9 anos",
  "Pornografia leve.",
  "Um gordo que dorme dentro do banheiro do McDonalds",
  "Depilar as bolas",
  "Porno de ovelhas",
  "Allahu Akbar",
  "Um longo, brilhante, grosso penis.",
  "Comunistas de merda",
  "Karl Marx",
  "2 girls 1 cup",
  "Donald Trump",
  "Viver no porão dos seus avós, ver anime e ser obeso.",
  "Nigga.",
  "Estupro consensual",
  "Nada.",
  "Vegetarianos.",
  "36 horas de masturbação intensa.",
  "Agenda feminista",
  "Dividir por 0",
  "Ebola.",
  "Correr nu pela casa",
  "Pedras no fim",
  "Um saco de feijões mágicos.",
  "Silêncio.",
  "Diarreia que nunca acaba.",
  "Agricultura.",
  "Carne de cavalo",
  "Ciência.",
  "Injeções hormonais",
  "A minha ex-mulher.",
  "Puberdade.",
  "Trabalhos",
  "Cuidados hospitalares.",
  "Uma metralhadora",
  "Não usar calças",
  "Netflix.",
  "Justin Bieber.",
  "Uma cara feia",
  "Testículos",
  "Sonhos molhados.",
  "Seleção natural.",
  "Os meus genitais",
  "Pessoas pobres",
  "Pessoas castanhas",
  "Orgasmo feminino",
  "Ser gordo e estúpido",
  "Esquecer de apagar o histórico da internet",
  "Holocausto: O musical.",
  "Usar supercola para evitar violação.",
  "Masturbar no banheiro do museu do Holocausto.",
  "Vagina.",
  "Levar bolada no queixo",
  "Esperma do bom.",
  "Swag.",
  "Um homem no clímax",
  "Tartarugas de assaltocom respiração ácida",
  "Forças negras e misteriosas fora do nosso controle",
  "Dar a luz ao AntiCristo.",
  "Mijo sexual.",
  "Nokia.",
  "Windows XP",
  "Crimes.",
  "Favelas",
  "PM do Rio.",
  "Petralhas.",
  "Tropa de Elite.",
  "Roubar do povo",
  "Não chegar a tempo ao Enem e ficar famoso no youtube.",
  "A minha vida.",
  "Rins.",
  "Beber Activia e não cagar",
  "Masturbar a barbie",
  "A minha namorada",
  "Os meus olhos",
  "Eu queria que o Brasil fosse de Portugal para participar da União Europeia",
  "Restos de esperma",
  "Assaltar um banco nos EUA.",
  "Pênis.",
  "Cheirar macacos",
  "Corrimento",
  "Beber o vômito de um cachorro",
  "Bater na mãe",
  "Morre diabo!",
  "Ver uma briga de drag queens.",
  "Baleia Azul.",
  "Gorila.",
  "Povos indígenas do Brasil.",
  "Andar com merda na boca",
  "Ter sexo no Sítio do Picapau Amarelo.",
  "Caguei nela",
  "Pênis cortado.",
  "Fumar.",
  "Hitler é seu namorado.",
  "Explodir",
  "Roubar cuecas de garotas de 12 anos",
  "Faca no cu",
  "Não tenho orgão.",
  "Piratas",
  "É muito grande",
  "Anime",
  "Mijar no sofá para marcar território",
  "Carne de humano",
  "Sentimentos",
  "Flores",
  "Camisinha",
  "Mulheres",
  "Doenças.",
  "Espanha",
  "7 de setembro de 1822",
  "Europa.",
  "EUA.",
  "Super bowl",
  "Namorada",
  "Tiro",
  "Arma",
  "Cabeça",
  "Sangue",
  "Foder",
  "Gordos mortos",
  "Rico",
  "Ser pobre",
  "Falso",
  "Verdadeiro",
  "Moedas",
  "Putinha",
  "Vida",
  "Copa de 2014",
  "Sorte",
  "Azar.",
  "O negão da piroca",
  "O gemidão do whats",
  "Muçulmanos",
  "A Terra é plana",
  "Com Activia não Caguei",
  "Vladimir Putin",
  "Cu sangrando",
  "Fazer amor pelo bumbum",
  "Pagar mico em público",
  "Ladrão de vadias",
  "Limpar a bunda com papel crepom.",
  "Nudez.",
  "Leis",
  "Políticos brasileiros",
  "Meleca de nariz",
  "Sol.",
  "Dilma",
  "Xingar a tua mãe",
  "Taca-lhe pau",
  "Roubar cachaça de mendigo",
  "Teta de vidro",
  "Treta",
  "Buffet livre",
  "Smurfs mortos",
  "Gente fedida",
  "Jogar strip roleta russa",
  "Chupar o cu de um pombo.",
  "Como aumentar o tamanho do pênis.",
  "Vestir uma blusa feita de cabelos humanos virgens.",
  "Caralhos voadores.",
  "Dor anal.",
  "Xingar a mãe da namorada",
  "Matar uma foca bebé com a força do meu penis",
  "Orgias do Vaticano",
  "Cagar em cima da comida na frente de um sem teto esfomeado.",
  "Meninas católicas",
  "Repositório de esperma",
  "Quando cola o seu penis num poste congelado no inverno",
  "Uma vagina onde cabe um melão",
  "Muçulmanos enrolados em bacon",
  "Pêlos do cu",
  "Geladinho de sêmen",
  "Ter sexo anal com outro homem mas dizer \"no homo\" depois.",
  "Violar um tetraplégico porque ele não se consegue defender",
  "Aquele homem obeso a \"meter a mão na massa\" no canto.",
  "Contratar uma prostituta, matá-la e comê-la",
  "Matar um cego à pedrada porque ele nunca verá as pedras chegando",
  "O bigode da sua tia",
  "Um dildo barato que estraga após uma utilização",
  "Violar menininhas no metrô",
  "Um javali a violar o Temer",
  "Pornografia da mocidade carioca.",
  "5 senegaleses munidos de penis de 20 cms",
  "A festa de Auschwitz",
  "Um ritual sexual de uma tribo africana",
  "Espancar órfãos",
  "Um filme antigo da primeira experiência sexual da minha avó.",
  "Estar na varanda, sem camisa, com uma sniper a alvejar judeus",
  "Usar o celular como vibrador",
  "Limpar vigorosamente o pênis da minha filha",
  "Uma stripper com lepra",
  "Ursinho Pooh usando um pote de mel para asfixia auto-erótica",
  "Servir carne grelhada na ala dos queimados do hospital",
  "Um rato a tentar fugir de dentro de uma vagina",
  "Aborto depois do nascimento",
  "Morte por esperma",
  "Prostitutas do século XVI",
  "Escrever palavras porcas ao jogar stop com crianças",
  "Ser penetrado por um taco de beisebol com arame farpado",
  "Filho da puta",
  "Uma colher de sopa de Ébola",
  "Uma piada insensível sobre pirocas",
  "Impotência",
  "Ficar com o sabonete na mão durante o banho da prisão apenas para ser violado pelo companheiro de cela.",
  "Feito, já não é incesto, é necrofilia",
  "Orgia de sexo anal",
  "Chupar todo o esperma do pênis do padrasto",
  "Não é gay se não tiver prazer",
  "Nada melhor que a mão áspera e grossa do meu padrasto",
  "Fetiche de pés",
  "Vagina com os lábios caídos até aos joelhos",
  "A grande, grossa e muito usada pica de um preto",
  "Violar o Lula na prisão",
  "Imbrochável",
  "Um penis grande e “a moda francesa”",
  "Apanhar a avó comendo o avô por trás com um dildo",
  "Afogar o ganso",
  "Uma orgia no vestiário da seleção brasileira.",
  "Remover pêlos do cu com o pé",
  "O gordo do Faustão",
  "Sexo anal com Kid Bengala",
  "Típica garota branca",
  "Masturbar ao ver porno de estupro",
  "O meu pequeno penis asiático",
  "Sentar num sanitário",
  "Pegar todas as sete Esferas do Dragão para desejar ter cuecas limpas",
  "O meu cu branco",
  "Bloquinhos de carnaval",
  "PCC",
  "Ir para a universidade conseguir um diploma para trabalhar no McDonalds",
  "Fazer sexo com mulheres gordas e em seguida terminar com elas",
  "Sexo consensual",
  "Ficar nu e ver Anime",
  "Ficar sem semen",
  "Abdomens espetaculares",
  "Make Brasil Great Again",
  "Estado Novo",
  "O petróleo é nosso!",
  "Motosserras no lugar de mãos",
  "O meu irmão estranho",
  "O homem do leite",
  "Dizer “eu te amo”",
  "O meu cu preto",
  "Roubar sinos",
  "Não usar calças",
  "Invadir a Polônia",
  "Calças muito justas",
  "Fotografias de tetas",
  "Jogar um virgem num vulcão",
  "Uma ereção que dura mais do que 4 horas",
  "Vender o seu bebé durante a Black Friday",
  "1, 2, 3, 4 ninjas",
  "Atirar microfones",
  "Uma chinesa vendendo cão frito às escondidas na 25 de março",
  "Adotar um vaga-lume mágico.",
  "Picas grandes e boas",
  "Cubo mágico",
  "Abstinência",
  "Um homem no clímax",
  "Segurar uma criança e peidar em cima dela.",
  "Ver a avó nua.",
  "Usar a espada de D. Pedro Primeiro como dildo no cu de um nordestino",
  "Ser raptado pelo Michael Jackson",
  "Lambuzar o pênis com manteiga",
  "Ir ao banheiro só para ver se não borrou as cuecas.",
  "Cortar os pentelhos com uma motosserra",
  "Mentir",
  "Raramente tomar banho",
  "Uma dentadura postiça",
  "Almoçar um belo prato de pau",
  "Tudo para o caralho, ganhei esta rodada",
  "Corrigir os gagos com uma bofetada",
  "Um penico voador",
  "Sensação de orgulho depois de esvaziar o intestino em menos de 5 segundos",
  "Sensação de união depois da limpeza étnica.",
  "Tão aliviante quanto um peido silencioso numa noite quente de verão",
  "Questionar o sentido da vida de forma leviana.",
  "Coçar o intestino grosso",
  "Palitar os dentes com um dardo.",
  "Fazer uma tatuagem em homenagem a buceta da tua mãe",
  "Descascar pedra",
  "Um preto que só diz: “Nigga”",
  "Eu sou japonês, não sou chinês",
  "A tua esbelta vagina",
  "Um Cristão não teme!",
  "Buceta",
  "Enfiarem uma buceta na minha boca",
  "Mandar uma nude num grupo de 30 pessoas",
  "Uma prostituta com pinto",
  "Um micropênis empolgado",
  "Um estilo de vida sexual exótico",
  "Tigres com Síndrome de Down",
  "Se sentir o máximo pelo seu pênis ter um centímetro a mais do que o da sua namorada",
  "Memórias de um excitante passado",
  "Masturbar-se pensando na sua ex",
  "Urinar sêmen de tanto tempo que não se masturba",
  "Aquele surubão",
  "Masturbar o pênis alheio",
  "Amor",
  "Um dildo broxa",
  "Rituais de invocação demoníaca",
  "Beijo grego",
  "Sua irmã gostosa",
  "Sertanejo universitário",
  "Sexo oral em si mesmo",
  "Lucifer",
  "Fica perdido numa ilha deserta apenas com a companhia de Wilson",
  "Voyeurismo",
  "Um discurso da Dilma",
  "Lula livre",
  "Fazer um discurso bonito cheio de palavras complicadas que ninguém entende",
  "O Santo Graal",
  "Albert Einstein usando roupas íntimas femininas em um desfile de moda",
  "Onde estou? Estou em Alagoinhas",
  "Um porco capitalista",
  "Um político honesto que tenta fazer o melhor para a sociedade",
  "Um dildo de 36cm",
  "Uma buceta peluda",
  "Um musical de escola infantil",
  "Criar e guardar clones num laboratório secreto para transplante de órgãos",
  "Dedo no cu e gritaria",
  "O casamento vermelho",
  "Anões fantasiados de animais",
  "Autistas de estimação",
  "Fazer sexo com uma gorda com mais de 150kg e ficar por baixo",
  "Uma gorda com tesão",
  "Um jovem branco loiro de olhos azuis",
  "Fazer o que dizem os seus demônios interiores",
  "A chacina do Carandiru",
  "SUA MÃE",
  "Sexo oral na direção",
  "Conselhos de um velho e sábio homem negro",
  "Cyberbullying",
  "Calcinhas usadas",
  "Friendzone",
  "Carreta furacão",
  "Aumentar o pênis usando as propagandas do xvideos",
  "Comer o cu de curioso",
  "Gol da Alemanha!",
  "Gol da Alemanha!",
  "Gol da Alemanha!",
  "Gol da Alemanha!",
  "Gol da Alemanha!",
  "Gol da Alemanha!",
  "Gol da Alemanha!",
  "A eterna memória do 7 a 1",
  "O sangue de Jesus tem poder, faz o inferno estremecer, o sangue de Jesus tem poder, faz o satanás correr e o milagre acontecer",
  "A vaca da sua mãe",
  "50 mil volts direto nos mamilos",
  "Um colombiano de 100kg dando uma voadora nas suas costas",
  "A vagina da Hebe Camargo",
  "Uma arca de noé com aleijados no lugar dos animais",
  "Acariciar os outros sem permissão",
  "Smigol",
  "Um anel que te deixa invisível",
  "Meu precioso",
  "EU QUERO TRUCO PORRA!!!!",
  "A vagina da minha namorada",
  "Seu ouvido",
  "Minha vagina",
  "Um pau muito duro a ponto de doer",
  "Trepada bem feita",
  "Rapidinha",
  "Uma buceta peluda",
  "Uma vagina apertadinha",
  "Farmar aura",
  "NPCs",
  "Pessoas que levam o jogo a sério",
  "A arma de Portal.",
  "Jogos de sobrevivência",
  "Aquelas pessoas que ainda jogam Pokémon Go.",
  "Um lançador de mísseis",
  "Os campers de merda",
  "Angry Birds",
  "Músicas de jogos que ficam no ouvido.",
  "Dungeons and Dragons.",
  "Aquela personagem de jogo que parece uma mulher mas na verdade é um homem",
  "Dar rage quit.",
  "Ser mau num jogo.",
  "Noobs.",
  "Jogadores casuais",
  "Jogos indie.",
  "League of Legends",
  "Aqueles retardados que pensam que a personagem principal do The Legend of Zelda é a Zelda.",
  "Bugs engraçados",
  "Spoilers",
  "Simuladores de relacionamentos",
  "Pokémon",
  "Jesus voltou!",
  "Fingir ser bonzinho apenas para ir para o céu e chupar o pinto de Deus",
  "Máfia amadora",
  "Cu da Anitta",
  "Baleias cometendo suicídio ao som de Enya",
  "Nudes",
  "Terraplanistas",
  "Pata de camelo",
  "Um padre, um pastor e um rabino",
  "Pornô gospel",
  "Pirocóptero",
  "Penetração quíntupla",
  "Pacto com o demônio",
  "Festas de swing em casas de repouso",
  "Um par de ingressos pro show do Restart",
  "Fogueira de livros",
  "Produção de lança perfumes",
  "Jogos de azar",
  "Um descontinho bacana",
  "Aulas de fio terra com Edward Mãos de Tesoura",
  "Pagode dos anos 90",
  "Um helicóptero com meia tonelada de cocaína",
  "Dollynho, o seu amiguinho",
  "Contrabandear drogas e celulares para presídios",
  "Sentir a adrenalina de passar um mês nas florestas da Austrália",
  "Pergunta lá no Posto Ipiranga",
  "Pikachu",
  "Ousadia e alegria",
  "Uma piada sem graça",
  "Zeca Paugordinho",
  "Thais Carla",
  "Jair bolsonaro",
  "Faz o L",
  "Estupro de incapaz",
  "Comer uma cadeirante",
  "Menines",
  "Comer um traveco só pra achar que meu pau atravessou a gostosa",
  "Black lives matter",
  "White lives matter",
  "Homicídio mamoso",
  "Quando minha meio irmã fica presa na máquina de lavar roupa",
  "É o Brazino",
  "O restaurante casa de grelhados do hitler",
  "Brincar de Starwars com a nova prudence na brotheragem",
  "Cheirar cocaína no pau do traveco",
  "Sem olho no olho, no homo",
  "Pau não tem ombro!",
  "Racismo inverso",
  "Punheta medicinal",
  "Porque negros não tem pais",
  "Ir comprar cigarro",
  "Pronome neutro",
  "Na chuva de pica se escolhe a menor",
  "Quero que o mundo acabe em rola só para eu morrer engasgado",
  "Só comer mudas porque quem cala consente",
  "Mendigo comedor",
  "Policial militar negro",
  "Eu duvido",
  "Não é micropênis, é perspectiva",
  "Fazer turismo sexual na Ucrânia",
  "Calabreso",
  "Fazer o pacto com o diabo para ser o escolhido de Deus",
  "Crianças com câncer",
  "Bater punheta no carro de vidro aberto",
  "Começar a beber às 10 da manhã",
  "Fazer sexo com um traveco",
  "Meu pau no seu ouvido",
  "Explicar o seu histórico da internet para a Polícia Federal",
  "Trocar nudes com o agiota para conseguir estender o prazo da dívida",
  "Um áudio de 5 minutos do ex chorando bêbado às 3 da manhã",
  "Fingir um desmaio repentino para não ter que pagar o lanche",
  "Um Pix de 15 mil reais que acabou caindo na conta errada",
  "Um anão idoso e muito musculoso com a roupa do Homem-Aranha",
  "Agredir um vizinho no supermercado para pegar a última bandeja de carne",
  "Ser cancelado na internet por ter xingado um cachorro caramelo",
  "Descobrir meses depois que a sua amante online era, na verdade, sua tia",
  "Um Celta rebaixado com caixa de som tocando funk em frente à porta do hospital",
  "Cigarro de café da manhã",
  "Banheirão",
  "Dar banho no peixe",
  "Levar a avó no jiu-jitsu",
  "Beber até o cu fazer bico",
];

const expansions = {
  "pack_amigos": {
    id: "pack_GMD",
    name: "Cartas GMD",
    blackCards: [
      "No último final de semana, o VL gozou durante o sono sonhando com ________.",
      "A pior coisa que você pode dizer pro Arthur é ________.",
      "A pior coisa que você pode dizer pro Otávio é ________.",
      "A pior coisa que você pode dizer pro Ruilce é ________.",
      "A pior coisa que você pode dizer pro Tuti é ________.",
      "A pior coisa que você pode dizer pro Fernando é ________.",
      "A pior coisa que você pode dizer pro Giuliano é ________.",
      "A pior coisa que você pode dizer pro Gabriel é ________.",
    ],
    whiteCards: [
      "Marcello",
      "Didi",
      "Strike 1",
      "Strike 2",
      "Strike 3",
      "O tio do Ruilce na frente de uma escola",
      "Primeiro o pauzinho, depois o dedinho",
      "Olhar para meninas no ônibus e falar que comi para os meus amigos",
      "Pedrinho",
      "Senhores, me caguei",
      "Meu maior inimigo é meu lençol cagado",
      "Gozar na pia do companheiro de quarto porque é legal",
      "Cheguei mozinho",
      "Cala boca filha da puta!!!",
      "Guys! Tive uma ideia",
      "chegai, chegai, chegai…",
      "Os 3 Strikes",
      "Elfo autista",
      "Papito",
      "Caminho de São Thiago",
      "Piroca +5",
      "Hypergato",
      "A fantástica fábrica de estórias do VL",
      "Ser habilitado para matar veados",
      "Ter a carteirinha do mensa",
      "Caaampeeeão! (Leia triste, como se simba tivesse morrido em sua frente, ou o otávio)",
      "Ruilce",
      "Tuti",
      "Otávio",
      "Fernando",
      "Giuliano",
      "Gabriel",
      "Socar uma velha",
      "Minha mãe é gostosa",
      "Já assisti filme esse ano",
      "Dar a desculpa que é seu aniversário para não sair com seus amigos.",
      "Buceta couveflor",
      "Não posso, é aniversário da minha mãe",
      "Estar de pau duro de tanguinha no meio do puteiro",
      "Francyne planeta anão.",
      "Vai se foder VL",
      "Eu amo... o Canadá",
      "Ruilce, to sem cueca...",
      "There's a vagina on your neck",
      "No meu momento mais hétero, eu virei gay",
    ]
  }
};

module.exports = { blackCards, whiteCards, expansions };
